### ISSUE TITLE
UMNNMAFFlow.invert argument missmatch in ToyExperiments.py

### ISSUE THREAD

**Issue by weissercn** [AWehenkel/UMNN#3]
When running ToyExperiments.py, I run into an issue with the UMNNMAFFlow.invert function. As defined in UMNNMAFFlow.py it only takes arguments "z" and "context". However, the arguments given are z, 5, and "ParallelSimpler". Removing the second argument (5) makes the required plot, however, I am not sure what it is supposed to do.

I can send a pull request deleting the second argument. 

Creating model...
Model created.
epoch: 0 - Train loss: 6.782076 - Test loss: 6.447329 - Elapsed time per epoch 0.064852 (seconds)
Traceback (most recent call last):
  File "ToyExperiments.py", line 186, in <module>
    train_toy(toy, load=args.load, folder=args.folder)
  File "ToyExperiments.py", line 163, in train_toy
    summary_plots(x, x_test, folder, epoch, model, ll_tot, ll_test)
  File "ToyExperiments.py", line 70, in summary_plots
    x_pred = model.invert(z, 5, "ParallelSimpler")
TypeError: invert() takes from 2 to 3 positional arguments but 4 were given

**Comment by AWehenkel** [comment]
Hi Constantin,
Ouch, this is probably due to an unwanted commit, I am going to clean that. Meanwhile, you may be interested in looking at my other implementation of UMNNs (as well as affine normalizing flows) there https://github.com/AWehenkel/Normalizing-Flows. This second repo is way cleaner although it does not implement all the original paper's experiments.
Thanks for pointing that! 
Best,
Antoine

**Comment by weissercn** [comment]
Thank you! I am going to look into the github.com/bayesiains/nflows implementation!
